//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.Detail_Commande = new HashSet<Detail_Commande>();
        }
    
        public string Id_commande { get; set; }
        public string Id_Client { get; set; }
        public Nullable<System.DateTime> Date_Commande { get; set; }
        public string DES_Commande { get; set; }
        public string Nom_Vendeur { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Commande> Detail_Commande { get; set; }
    }
}
