//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Commande
    {
        public string Id_Produit { get; set; }
        public string Id_commande { get; set; }
        public Nullable<int> Quantite { get; set; }
        public Nullable<double> réduction { get; set; }
        public Nullable<double> Prix { get; set; }
        public Nullable<double> Montant { get; set; }
        public Nullable<double> Montant_total { get; set; }
    
        public virtual Commande Commande { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
